faiss_db:
  collection_name: "document_portal"
  
embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "llama-3.1-8b-instant"
    temperature: 0
    max_output_tokens: 2048

  google:
      provider: "google"
      model_name: "gemini_2.0-flash"
      temperature: 0
      max_output_tokens: 2048

  openai:
      provider: "openai"
      model_name: "gpt-4o"
      temperature: 0
      max_output_tokens: 2048